name: CI/CD
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up
        run: make install
      # - name: Run Tests
      #   run: make test
      - name: Build
        run: make build 
